### ISSUE TITLE
 search table error: _SYS_AFL.AFLPAL:AUTOML_FIT Error message when execute example -- hana-ml_Tutorial_Auto_ML

### ISSUE THREAD

**Issue by johnnyssr** [SAP-samples/hana-ml-samples#36]
Hi developer,

When I try to run code example of Auto_ML, there is an error when execute 
# training
try:
    **auto_c.fit(data=df_diabetes_train, key="ID")**
except Exception as e:
    raise e

**Error Message:**
ERROR:hana_ml.algorithms.pal.auto_ml:(423, 'AFL error: "JOHNNY"."(DO statement)": line 60 col 1 (at pos 3912): search table error: _SYS_AFL.AFLPAL:AUTOML_FIT: [423] (range 3) AFL error exception: exception 73003003: PAL error[$ERROR_CODE$]:Pipeline Error: $MSG$; $[1]$=Operator; $[2]$=Imputer; $[3]$= does not exist\n')
Traceback (most recent call last):
  File "C:\Users\I354885\AppData\Local\Programs\Python\Python312\Lib\site-packages\hana_ml\algorithms\pal\auto_ml.py", line 803, in _fit
    self._call_pal_auto(conn,
  File "C:\Users\I354885\AppData\Local\Programs\Python\Python312\Lib\site-packages\hana_ml\algorithms\pal\pal_base.py", line 916, in _call_pal_auto
    self.execute_statement, materialize_dict = call_pal_auto_with_hint(conn_context,......
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I checked in HANA, there is no table named _SYS_AFL.AFLPAL:AUTOML_FIT

Could you please help to check this?

Best Regards,
Johnny

**Comment by raymondyao** [comment]
Hi Johnny,

 _SYS_AFL.AFLPAL:AUTOML_FIT is the procedure from AFL module. Please make sure that you have installed the AFL plugins, enabled scriptserver and had PAL execution privilege.

BR,
Raymond

**Comment by johnnyssr** [comment]
Hi Raymond,

Thanks for your quickly reply, as you can see I have installed AFL add-on

![image](https://github.com/user-attachments/assets/5c89310e-c956-439e-8d18-f93deedef9fc)


I didn't find a procedure name with AFLPAL but find a procedure name PAL_AUTOML_FIT:

![image](https://github.com/user-attachments/assets/7e55aec2-f23e-4af3-b5c4-b68e1df42e41)


Is there any thing I missed?

Best Regards,
Johnny

**Comment by raymondyao** [comment]
Hi Johnny,

From the error message, the error is mainly due to the operators missing in the config dict. You can resolve the issue by 
1) upgrade your AFL/PAL to the latest one
2) remove the unsupported operator in your HANA instance (Imputer) in the config_dict

Best,
Raymond

**Comment by johnnyssr** [comment]
Hi Raymond,

1.  I have installed the latest HANA and AFL add-on
2.  Could you tell me how to remove operator? How to adjust in config_dict? because I just start to learn this hana-ml and try to run a example

Best Regards,
Johnny

**Comment by raymondyao** [comment]
Hi Johnny,

There're several ways to manage the config_dict (searching space). You can use our visualization tool.

from hana_ml.visualizers.automl_config import AutoMLConfig

automl_config = AutoMLConfig()

#do some modification

my_config_dict = automl_config.get_config_dict()


Best,
Raymond
